from __future__ import annotations

import argparse
import json
from pathlib import Path

from a_bot_config import AConfig
from a_bot_trace import load_trace_events, render_summary_markdown, summarize_trace_events
from a_news_tracker import (
    build_a_news_tracker_report,
    build_unknown_news_term_report,
    render_a_news_tracker_markdown,
    render_unknown_terms_markdown,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Offline summary for an A-bot analysis-mode run.")
    parser.add_argument(
        "path",
        help="Run directory or trace_events.jsonl generated by the A bot analysis mode.",
    )
    parser.add_argument(
        "--rewrite-summary",
        action="store_true",
        help="Rewrite session_summary.json and session_summary.md in the run directory.",
    )
    return parser.parse_args()


def resolve_run_dir(path_str: str) -> Path:
    path = Path(path_str).expanduser().resolve()
    if path.is_file():
        return path.parent
    return path


def print_summary(summary: dict) -> None:
    print("A Bot Run Summary")
    print(f"Total events: {summary.get('total_events', 0)}")
    print(f"Estimated final MTM PnL: {summary.get('estimated_final_mtm_pnl')} ({summary.get('estimated_final_mtm_basis')})")
    print(f"Relevant A structured earnings: {summary.get('a_relevant_structured_earnings_count', 0)}")
    print(f"Irrelevant structured items: {summary.get('a_irrelevant_structured_count', 0)}")
    print(f"Relevant A unstructured news: {summary.get('a_relevant_unstructured_count', 0)}")
    print(f"Passive fills: {summary.get('passive_fills', 0)}")
    print(f"Aggressive fills: {summary.get('aggressive_fills', 0)}")
    print(f"Largest long inventory: {summary.get('largest_inventory_long', 0)}")
    print(f"Largest short inventory: {summary.get('largest_inventory_short', 0)}")
    print(f"Average inventory: {summary.get('average_inventory', 0.0):.2f}")
    print(f"Average earnings inventory: {summary.get('average_earnings_inventory', 0.0):.2f}")
    print(f"Average MM inventory: {summary.get('average_mm_inventory', 0.0):.2f}")
    print(f"Average quoted spread: {summary.get('average_quoted_spread')}")
    print(f"Observe-only decisions: {summary.get('observe_only_count', 0)}")
    print(f"Budget shift active (ms): {summary.get('budget_shift_active_ms', 0)}")
    print("")
    print("PnL by market:")
    for market, pnl in (summary.get("pnl_by_market") or {}).items():
        print(f"  {market}: {pnl}")
    print("")
    print("PnL by strategy family:")
    for strategy, pnl in (summary.get("pnl_by_strategy_family") or {}).items():
        print(f"  {strategy}: {pnl}")
    print("")
    print("PnL by action class:")
    for action_class, pnl in (summary.get("pnl_by_action_class") or {}).items():
        print(f"  {action_class}: {pnl}")
    print("")
    print("Fills by intent:")
    for intent, count in (summary.get("fills_by_intent") or {}).items():
        print(f"  {intent}: {count}")
    print("")
    print("Fills by action class:")
    for action_class, count in (summary.get("fills_by_action_class") or {}).items():
        print(f"  {action_class}: {count}")
    print("")
    print("Fills by overlay:")
    for overlay, count in (summary.get("fills_by_overlay") or {}).items():
        print(f"  {overlay}: {count}")
    print("")
    print("Mode durations (ms):")
    for mode, duration in (summary.get("mode_durations_ms") or {}).items():
        print(f"  {mode}: {duration}")
    print("")
    print("Top no-action reasons:")
    for reason, count in list((summary.get("most_common_no_action_reasons") or {}).items())[:10]:
        print(f"  {reason}: {count}")
    print("")
    print("Average fill markouts by intent:")
    for intent, window_map in (summary.get("fill_markouts_by_intent") or {}).items():
        formatted = ", ".join(f"{window}={value:.2f}" for window, value in window_map.items())
        print(f"  {intent}: {formatted}")
    print("")
    print("Average markouts by action class:")
    for action_class, window_map in (summary.get("markouts_by_action_class") or {}).items():
        formatted = ", ".join(f"{window}={value:.2f}" for window, value in window_map.items())
        print(f"  {action_class}: {formatted}")
    print("")
    print("Top losing strategy families:")
    for row in summary.get("top_losing_strategy_families") or []:
        print(
            f"  {row.get('strategy_family')}: total={row.get('total_pnl')} "
            f"realized={row.get('realized_pnl')} unrealized={row.get('unrealized_pnl')}"
        )
    print("")
    print("Top losing signal episodes:")
    for row in summary.get("top_losing_signal_episodes") or []:
        print(
            f"  {row.get('market_key')} {row.get('strategy_family')} {row.get('signal_id')}: "
            f"total={row.get('total_pnl')} fills={row.get('fill_count')} qty={row.get('fill_qty')}"
        )
    print("")
    print("Derived signal counts:")
    for strategy_family, count in (summary.get("derived_signal_counts") or {}).items():
        print(f"  {strategy_family}: {count}")
    print("")
    print("A episode summaries:")
    for row in summary.get("a_episode_summaries") or []:
        print(
            f"  {row.get('signal_id')}: tick={row.get('tick')} fair_jump={row.get('fair_jump')} "
            f"mode_before={row.get('mode_before_news')} shock_qty={row.get('shock_take_qty')} "
            f"peak_total={row.get('peak_total_inventory')} peak_earnings={row.get('peak_earnings_inventory')} "
            f"unwind_ms={row.get('unwind_time_ms')} next_during_unwind={row.get('next_earnings_arrived_during_unwind')} "
            f"cycle_pnl={row.get('cycle_pnl_by_strategy_owner')}"
        )
    print("")
    print("A MM loss by mode:")
    for mode, stats in (summary.get("a_mm_loss_by_mode") or {}).items():
        print(f"  {mode}: {stats}")
    print("")
    print("A strategy breakdown:")
    for key, value in (summary.get("a_strategy_breakdown") or {}).items():
        print(f"  {key}: {value}")
    print("")
    print("B cost-adjusted residual stats:")
    b_stats = summary.get("b_cost_adjusted_residual_stats") or {}
    print(f"  composite_basis: {b_stats.get('composite_basis')}")
    for strike, stats in (b_stats.get("by_strike") or {}).items():
        print(f"  strike {strike}: {stats}")
    print("")
    print("B strategy block reasons:")
    for reason, count in (summary.get("b_strategy_block_reasons") or {}).items():
        print(f"  {reason}: {count}")
    print("")
    print("Trace volume summary:")
    volume = summary.get("trace_volume_summary") or {}
    print(f"  event_counts: {volume.get('event_counts')}")
    print(f"  symbol_counts: {volume.get('symbol_counts')}")


def main() -> None:
    args = parse_args()
    run_dir = resolve_run_dir(args.path)
    events = load_trace_events(run_dir)
    summary = summarize_trace_events(events)
    print_summary(summary)

    if args.rewrite_summary:
        summary_json_path = run_dir / "session_summary.json"
        summary_md_path = run_dir / "session_summary.md"
        tracker_json_path = run_dir / "a_news_tracker.json"
        tracker_md_path = run_dir / "a_news_tracker.md"
        unknown_json_path = run_dir / "unknown_a_news_terms.json"
        unknown_md_path = run_dir / "unknown_a_news_terms.md"
        tracker_report = build_a_news_tracker_report(events, config=AConfig())
        unknown_terms_report = build_unknown_news_term_report(events)
        headline_rows = tracker_report.get("headline_analyses") or []
        recommendation_rows = tracker_report.get("term_recommendations") or []
        summary["a_news_summary"] = {
            "headline_count": len(headline_rows),
            "traded_count": sum(1 for row in headline_rows if row.get("traded")),
            "missed_no_trade_count": sum(1 for row in headline_rows if row.get("verdict") == "missed_no_trade"),
            "undersized_count": sum(1 for row in headline_rows if row.get("verdict") == "undersized"),
            "wrong_direction_count": sum(1 for row in headline_rows if row.get("verdict") == "wrong_direction"),
            "a_news_pnl": round(float((summary.get("pnl_by_strategy_family") or {}).get("a_news", 0.0)), 4),
            "fill_count": int(((summary.get("strategy_family_stats") or {}).get("a_news") or {}).get("fill_count", 0)),
            "fill_qty": int(((summary.get("strategy_family_stats") or {}).get("a_news") or {}).get("fill_qty", 0)),
            "top_recommendations": [
                {
                    "term": row.get("term"),
                    "suggested_action": row.get("suggested_action"),
                    "suggested_weight_delta": row.get("suggested_weight_delta"),
                }
                for row in recommendation_rows
                if row.get("suggested_action") not in {None, "review"}
            ][:10],
        }
        with summary_json_path.open("w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2, sort_keys=True)
        run_id = events[0].get("run_id") if events else "unknown"
        with summary_md_path.open("w", encoding="utf-8") as handle:
            handle.write(render_summary_markdown(summary, str(run_id), run_dir))
        with tracker_json_path.open("w", encoding="utf-8") as handle:
            json.dump(tracker_report, handle, indent=2, sort_keys=True)
        with tracker_md_path.open("w", encoding="utf-8") as handle:
            handle.write(render_a_news_tracker_markdown(tracker_report, run_dir))
        with unknown_json_path.open("w", encoding="utf-8") as handle:
            json.dump(unknown_terms_report, handle, indent=2, sort_keys=True)
        with unknown_md_path.open("w", encoding="utf-8") as handle:
            handle.write(render_unknown_terms_markdown(unknown_terms_report, run_dir))


if __name__ == "__main__":
    main()
