from __future__ import annotations

import argparse
import json
from pathlib import Path

from a_bot_trace import load_trace_events, render_summary_markdown, summarize_trace_events


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Offline summary for an A-bot analysis-mode run.")
    parser.add_argument(
        "path",
        help="Run directory or trace_events.jsonl generated by the A bot analysis mode.",
    )
    parser.add_argument(
        "--rewrite-summary",
        action="store_true",
        help="Rewrite session_summary.json and session_summary.md in the run directory.",
    )
    return parser.parse_args()


def resolve_run_dir(path_str: str) -> Path:
    path = Path(path_str).expanduser().resolve()
    if path.is_file():
        return path.parent
    return path


def print_summary(summary: dict) -> None:
    print("A Bot Run Summary")
    print(f"Total events: {summary.get('total_events', 0)}")
    print(f"Estimated final MTM PnL: {summary.get('estimated_final_mtm_pnl')} ({summary.get('estimated_final_mtm_basis')})")
    print(f"Passive fills: {summary.get('passive_fills', 0)}")
    print(f"Aggressive fills: {summary.get('aggressive_fills', 0)}")
    print(f"Largest long inventory: {summary.get('largest_inventory_long', 0)}")
    print(f"Largest short inventory: {summary.get('largest_inventory_short', 0)}")
    print(f"Average inventory: {summary.get('average_inventory', 0.0):.2f}")
    print(f"Average earnings inventory: {summary.get('average_earnings_inventory', 0.0):.2f}")
    print(f"Average MM inventory: {summary.get('average_mm_inventory', 0.0):.2f}")
    print(f"Average quoted spread: {summary.get('average_quoted_spread')}")
    print(f"Observe-only decisions: {summary.get('observe_only_count', 0)}")
    print(f"Budget shift active (ms): {summary.get('budget_shift_active_ms', 0)}")
    print("")
    print("Local processing durations (ms):")
    for metric, stats in (summary.get("local_processing_durations_ms") or {}).items():
        print(f"  {metric}: p50={stats.get('p50')} p95={stats.get('p95')} max={stats.get('max')}")
    print("")
    print("Fills by intent:")
    for intent, count in (summary.get("fills_by_intent") or {}).items():
        print(f"  {intent}: {count}")
    print("")
    print("Fills by overlay:")
    for overlay, count in (summary.get("fills_by_overlay") or {}).items():
        print(f"  {overlay}: {count}")
    print("")
    print("Mode durations (ms):")
    for mode, duration in (summary.get("mode_durations_ms") or {}).items():
        print(f"  {mode}: {duration}")
    print("")
    print("Top no-action reasons:")
    for reason, count in list((summary.get("most_common_no_action_reasons") or {}).items())[:10]:
        print(f"  {reason}: {count}")
    print("")
    print("Average fill markouts by intent:")
    for intent, window_map in (summary.get("fill_markouts_by_intent") or {}).items():
        formatted = ", ".join(f"{window}={value:.2f}" for window, value in window_map.items())
        print(f"  {intent}: {formatted}")


def main() -> None:
    args = parse_args()
    run_dir = resolve_run_dir(args.path)
    events = load_trace_events(run_dir)
    summary = summarize_trace_events(events)
    print_summary(summary)

    if args.rewrite_summary:
        summary_json_path = run_dir / "session_summary.json"
        summary_md_path = run_dir / "session_summary.md"
        with summary_json_path.open("w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2, sort_keys=True)
        run_id = events[0].get("run_id") if events else "unknown"
        with summary_md_path.open("w", encoding="utf-8") as handle:
            handle.write(render_summary_markdown(summary, str(run_id), run_dir))


if __name__ == "__main__":
    main()
